spring:
  application:
    name: demo
  data:
    redis:
      host: 122.51.221.6
      port: 30007
      password: JqA5i2JrtjpHTYDHiEDT
      database: 0
  rabbitmq:
    host: 122.51.221.6
    port: 30272
    virtual-host: md
    username: md
    password: 123
  datasource:
    url: jdbc:mysql://54.255.253.1:3306/nusteamproject1
    username: root
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.demo.Controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn





