spring:
  application:
    name: demo


  datasource:
    url: jdbc:mysql://localhost:3306/nusteamproject1
    username: root
    password: Zbw01020304

mybatis:
  configuration:
    map-underscore-to-camel-case: true

