spring:
  application:
    name: demo
  rabbitmq:
    host: 13.251.129.185
    port: 31681
    virtual-host: md
    username: md
    password: 123

  datasource:
    url: jdbc:mysql://localhost:3306/nusteamproject1
    username: root
    password: Zbw01020304
  data:
    redis:
      password: 1234
      host: 13.229.95.80
      port: 6379
      database: 0

mybatis:
  configuration:
    map-underscore-to-camel-case: true

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.demo.Controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn




