server:
  port: 8084

spring:
  application:
    name: Post-service
  cloud:
    nacos:
      server-addr: 192.168.201.128:8848
  datasource:
    url: jdbc:mysql://localhost:3306/nusteamproject1
    username: root
    password: lihao8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true

knife4j:
  enable: true
  openapi:
    title: 商品服务接口文档
    description: "信息"
    email: zhanghuyi@itcast.cn
    concat: 虎哥
    url: https://www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.example.demo.post.Controller



