server:
  port: 8083

spring:
  application:
    name: Record-service
  cloud:
    nacos:
      server-addr: 13.251.129.185:29781 # nacos地址
  datasource:
    url: jdbc:mysql://localhost:3306/nusteamproject1
    username: root
    password: lihao8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true

knife4j:
  enable: true
  openapi:
    title: 商品服务接口文档
    description: "信息"
    email: zhanghuyi@itcast.cn
    concat: 虎哥
    url: https://www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.example.demo.record.Controller


